//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestVisioAutomation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestVisioAutomation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;autolayoutdrawing&gt;
        ///  &lt;page&gt;
        ///    &lt;renderoptions
        ///      usedynamicconnectors=&quot;true&quot;
        ///      scalingfactor=&quot;20&quot;
        ///    /&gt;
        ///    &lt;shapes&gt;
        ///      &lt;shape id=&quot;n1&quot; label=&quot;FOO1&quot; stencil=&quot;server_u.vss&quot; master=&quot;Server&quot; url=&quot;http://microsoft.com&quot; /&gt;
        ///      &lt;shape id=&quot;n2&quot; label=&quot;FOO2&quot; stencil=&quot;server_u.vss&quot; master=&quot;Email Server&quot; url=&quot;http://contoso.com&quot;/&gt;
        ///      &lt;shape id=&quot;n3&quot; label=&quot;FOO3&quot; stencil=&quot;server_u.vss&quot; master=&quot;Proxy Server&quot; url=&quot;\\isotope\public&quot; /&gt;
        ///      &lt;shape id=&quot;n4&quot; label=&quot;FOO4&quot; stencil=&quot;server_u.vss&quot; mast [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sampleflowchart1 {
            get {
                return ResourceManager.GetString("sampleflowchart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;autolayoutdrawing&gt;
        ///  &lt;page&gt;
        ///    
        ///  &lt;renderoptions
        ///      usedynamicconnectors=&quot;true&quot;
        ///      scalingfactor=&quot;20&quot;
        ///    /&gt;
        ///  &lt;shapes&gt;
        ///    &lt;shape id=&quot;n1&quot; label=&quot;8761|Gus&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Process&quot; /&gt;
        ///    &lt;shape id=&quot;n2&quot; label=&quot;0|ProABCS&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Process&quot; /&gt;
        ///    &lt;shape id=&quot;n3&quot; label=&quot;ABCS&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Decision&quot; /&gt;
        ///    &lt;shape id=&quot;n4&quot; label=&quot;Global Underwriting&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Decision&quot; /&gt;
        ///  &lt;/shapes&gt;
        ///
        ///  &lt;connectors&gt;
        ///    &lt;connector  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sampleflowchart2 {
            get {
                return ResourceManager.GetString("sampleflowchart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;autolayoutdrawing&gt;
        ///  &lt;page&gt;
        ///    
        ///  &lt;renderoptions
        ///    usedynamicconnectors=&quot;false&quot;
        ///    scalingfactor=&quot;20&quot;
        ///    /&gt;
        ///  &lt;shapes&gt;
        ///    &lt;shape id=&quot;n1&quot; label=&quot;8761|Gus&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Process&quot; /&gt;
        ///    &lt;shape id=&quot;n2&quot; label=&quot;0|ProABCS&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Process&quot; /&gt;
        ///    &lt;shape id=&quot;n3&quot; label=&quot;ABCS&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Data&quot; /&gt;
        ///    &lt;shape id=&quot;n4&quot; label=&quot;Global Underwriting&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Data&quot; /&gt;
        ///  &lt;/shapes&gt;
        ///
        ///  &lt;connectors&gt;
        ///    &lt;connector id=&quot;c1&quot;  fr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sampleflowchart3 {
            get {
                return ResourceManager.GetString("sampleflowchart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;autolayoutdrawing&gt;
        ///  &lt;page&gt;
        ///
        ///    &lt;renderoptions
        ///        usedynamicconnectors=&quot;true&quot;
        ///        scalingfactor=&quot;5&quot;
        ///    /&gt;
        ///  &lt;shapes&gt;
        ///    &lt;shape id=&quot;n1&quot; label=&quot;Decision1&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Decision&quot; /&gt;
        ///    &lt;shape id=&quot;n2&quot; label=&quot;Process2&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Process&quot; /&gt;
        ///    &lt;shape id=&quot;n3&quot; label=&quot;Data3&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Data&quot; /&gt;
        ///    &lt;shape id=&quot;n4&quot; label=&quot;Porcess4&quot; stencil=&quot;basflo_u.vss&quot; master=&quot;Process&quot; /&gt;
        ///    &lt;shape id=&quot;n5&quot; label=&quot;Data5&quot; stencil=&quot;basflo_u.vss&quot; mas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sampleflowchart4 {
            get {
                return ResourceManager.GetString("sampleflowchart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;orgchart&gt;
        ///  &lt;shape id=&quot;0&quot; name=&quot;Akuma&quot; /&gt;
        ///  &lt;shape id=&quot;1&quot; name=&quot;Ryu&quot; parentid=&quot;0&quot;/&gt;
        ///  &lt;shape id=&quot;2&quot; name=&quot;Ken&quot; parentid=&quot;0&quot;/&gt;
        ///  &lt;shape id=&quot;3&quot; name=&quot;Chun-Li&quot; parentid=&quot;2&quot;/&gt;
        ///&lt;/orgchart&gt;.
        /// </summary>
        internal static string sampleorgchart1 {
            get {
                return ResourceManager.GetString("sampleorgchart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos; ?&gt;
        ///&lt;VisioDocument key=&apos;819C3473406D7B85E75DD5087FBD5DDA90275AB23E709157F99645FB5B7A182D34B7AA0EA9BDAECA0B085495B82312D2BCA656D7AD2D81B533C7AF17990D26C1&apos; start=&apos;190&apos; metric=&apos;0&apos; DocLangID=&apos;1033&apos; buildnum=&apos;4518&apos; version=&apos;12.0&apos; xml:space=&apos;preserve&apos; xmlns:vx=&apos;http://schemas.microsoft.com/visio/2006/extension&apos; xmlns=&apos;http://schemas.microsoft.com/visio/2003/core&apos;&gt;&lt;DocumentProperties&gt;&lt;Creator&gt;esh038&lt;/Creator&gt;&lt;Template&gt;C:\Program Files\Microsoft Office\Office12\1033\NETW_U.VST&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_router__vdx {
            get {
                return ResourceManager.GetString("template_router__vdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;VisioDocument key=&quot;819C3473406D7B85E75DD5087FBD5DDA90275AB23E709157F99645FB5B7A182D34B7AA0EA9BDAECA0B085495B82312D2BCA656D7AD2D81B533C7AF17990D26C1&quot; start=&quot;190&quot; metric=&quot;0&quot; DocLangID=&quot;1033&quot; buildnum=&quot;4518&quot; version=&quot;12.0&quot; xml:space=&quot;preserve&quot; xmlns:vx=&quot;http://schemas.microsoft.com/visio/2006/extension&quot; xmlns=&quot;http://schemas.microsoft.com/visio/2003/core&quot;&gt;&lt;DocumentProperties&gt;&lt;Creator&gt;&lt;/Creator&gt;&lt;Company&gt;&lt;/Company&gt;&lt;BuildNumberCreated&gt;805312791&lt;/BuildNumberCreated&gt;&lt;BuildNumb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vdx_with_errors_1_vdx {
            get {
                return ResourceManager.GetString("vdx_with_errors_1_vdx", resourceCulture);
            }
        }
    }
}
