//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisioAutomation.Metadata.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisioAutomation.Metadata.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;table&gt;
        ///	&lt;row ID=&quot;cell_action_sec_actions&quot; Name=&quot;Actions.Action&quot; NameCode=&quot;Actions_Action&quot; NameFormatString=&quot;Actions.{0}.Action&quot; Object=&quot;shape-action&quot; NameType=&quot;named&quot; DataType=&quot;String&quot; ContentType=&quot;Formula&quot; Unit=&quot;Formula&quot; SectionIndex=&quot;visSectionAction&quot; RowIndex=&quot;visRowAction&quot; MinVersion=&quot;Visio2007&quot; CellIndex=&quot;visActionAction&quot; MSDN=&quot;http://msdn.microsoft.com/en-us/library/ms406240(loband).aspx&quot;/&gt;
        ///	&lt;row ID=&quot;cell_begingroup_sec_actions&quot; Name=&quot;Actions [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cells {
            get {
                return ResourceManager.GetString("cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;table&gt;
        ///  &lt;row ID=&quot;cellvalueenum_alignment_tabs&quot; Enum=&quot;TabAlignment&quot; Name=&quot;Left&quot; Value=&quot;&quot; AutomationConstant=&quot;visTabStopLeft&quot; /&gt;
        ///  &lt;row ID=&quot;cellvalueenum_alignment_tabs&quot; Enum=&quot;TabAlignment&quot; Name=&quot;Center&quot; Value=&quot;&quot; AutomationConstant=&quot;visTabStopCenter&quot; /&gt;
        ///  &lt;row ID=&quot;cellvalueenum_alignment_tabs&quot; Enum=&quot;TabAlignment&quot; Name=&quot;Right&quot; Value=&quot;&quot; AutomationConstant=&quot;visTabStopRight&quot; /&gt;
        ///  &lt;row ID=&quot;cellvalueenum_alignment_tabs&quot; Enum=&quot;TabAlignment&quot; Name=&quot;Decimal&quot; Value=&quot;&quot; Automa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cellvalues {
            get {
                return ResourceManager.GetString("cellvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;table&gt;
        ///  &lt;row ID=&quot;automationenum_visarcsweepflags&quot; Enum=&quot;VisArcSweepFlags&quot; Name=&quot;visArcSweepFlagConcave&quot; Value=&quot;0&quot; /&gt;
        ///  &lt;row ID=&quot;automationenum_visarcsweepflags&quot; Enum=&quot;VisArcSweepFlags&quot; Name=&quot;visArcSweepFlagConvex&quot; Value=&quot;1&quot; /&gt;
        ///  &lt;row ID=&quot;automationenum_visautoconnectdir&quot; Enum=&quot;VisAutoConnectDir&quot; Name=&quot;visAutoConnectDirNone&quot; Value=&quot;0&quot; /&gt;
        ///  &lt;row ID=&quot;automationenum_visautoconnectdir&quot; Enum=&quot;VisAutoConnectDir&quot; Name=&quot;visAutoConnectDirUp&quot; Value=&quot;1&quot; /&gt;
        ///  &lt;row ID=&quot;autom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string constants {
            get {
                return ResourceManager.GetString("constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;table&gt;
        ///  &lt;row ID=&quot;sec_1dendpoints&quot; Name=&quot;OneDEndpoints&quot; DisplayName=&quot;1D Endpoints&quot; Enum=&quot;visSectionObject&quot; /&gt;
        ///  &lt;row ID=&quot;sec_actions&quot; Name=&quot;Actions&quot; DisplayName=&quot;Actions&quot; Enum=&quot;visSectionAction&quot; /&gt;
        ///  &lt;row ID=&quot;sec_alignment&quot; Name=&quot;Alignment&quot; DisplayName=&quot;Alignment&quot; Enum=&quot;visSectionObject&quot; /&gt;
        ///  &lt;row ID=&quot;sec_annotation&quot; Name=&quot;Annotation&quot; DisplayName=&quot;Annotation&quot; Enum=&quot;visSectionAnnotation&quot; /&gt;
        ///  &lt;row ID=&quot;sec_character&quot; Name=&quot;Character&quot; DisplayName=&quot;Character&quot; Enum=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sections {
            get {
                return ResourceManager.GetString("sections", resourceCulture);
            }
        }
    }
}
