//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestVisioAutomation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestVisioAutomation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string sampleflowchart1 {
            get {
                return ResourceManager.GetString("sampleflowchart1", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string sampleflowchart2 {
            get {
                return ResourceManager.GetString("sampleflowchart2", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string sampleflowchart3 {
            get {
                return ResourceManager.GetString("sampleflowchart3", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string sampleflowchart4 {
            get {
                return ResourceManager.GetString("sampleflowchart4", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string sampleorgchart1 {
            get {
                return ResourceManager.GetString("sampleorgchart1", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string template_router__vdx {
            get {
                return ResourceManager.GetString("template_router__vdx", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string vdx_with_errors_1_vdx {
            get {
                return ResourceManager.GetString("vdx_with_errors_1_vdx", resourceCulture);
            }
        }
    }
}
