namespace VisioAutomation.UI
{
    public enum FillPattern
    {
        None = 0,
        Solid = 1,
        WideUpDiagonal = 2,
        WideCross = 3,
        WideDiagonalCross = 4,
        WideDownDiagonal = 5,
        WideHorz = 6,
        WideVert = 7,
        BackDotsMini = 8,
        HalfAndHalf = 9,
        ForeDotsMini = 10,
        ForeDotsNarrow = 11,
        ForeDotsWide = 12,
        ThickHorz = 13,
        ThickVertical = 14,
        ThickDownDiagonal = 15,
        ThickUpDiagonal = 16,
        ThickDiagonalCross = 17,
        BackDotsWide = 18,
        ThinHorz = 19,
        ThinVert = 20,
        ThinDownDiagonal = 21,
        ThinUpDiagonal = 22,
        ThinCross = 23,
        ThinDiagonalCross = 24,
        LinearLeftToRight = 25,
        LinearVertical = 26,
        LinearRightToLeft = 27,
        LinearTopToBottom = 28,
        LinearHorizontal = 29,
        LinearBottomToTop = 30,
        RectangularUpperLeft = 31,
        RectangularUpperRight = 32,
        RectangularLowerLeft = 33,
        RectangularLowerRight = 34,
        RectangularCenter = 35,
        RadialUpperLeft = 36,
        RadialUpperRight = 37,
        RadialLowerLeft = 38,
        RadialLowerRight = 39,
        RadialCenter = 40
    }
}