using System.Collections.Generic;
using SRCCON = VisioAutomation.ShapeSheet.SrcConstants;

namespace VisioPowerShell.Models
{
    public class PageCells : VisioPowerShell.Models.BaseCells
    {
        public string DrawingResizeType;
        public string DrawingScale;
        public string DrawingScaleType;
        public string DrawingSizeType;
        public string Height;
        public string InhibitSnap;
        public string LayoutAvenueSizeX;
        public string LayoutAvenueSizeY;
        public string LayoutAvoidPageBreaks;
        public string LayoutBlockSizeX;
        public string LayoutBlockSizeY;
        public string LayoutControlAsInput;
        public string LayoutDynamicsOff;
        public string LayoutEnableGrid;
        public string LayoutLineAdjustFrom;
        public string LayoutLineAdjustTo;
        public string LayoutLineJumpCode;
        public string LayoutLineJumpDirX;
        public string LayoutLineJumpDirY;
        public string LayoutLineJumpFactorX;
        public string LayoutLineJumpFactorY;
        public string LayoutLineJumpStyle;
        public string LayoutLineRouteExt;
        public string LayoutLineToLineX;
        public string LayoutLineToLineY;
        public string LayoutLineToNodeX;
        public string LayoutLineToNodeY;
        public string LayoutPlaceDepth;
        public string LayoutPlaceFlip;
        public string LayoutPlaceStyle;
        public string LayoutPlowCode;
        public string LayoutResizePage;
        public string LayoutRouteStyle;
        public string LayoutShapeSplit;
        public string Scale;
        public string ShadowObliqueAngle;
        public string ShadowOffsetX;
        public string ShadowOffsetY;
        public string ShadowScaleFactor;
        public string ShadowType;
        public string UIVisibility;
        public string Width;
        public string BottomMargin;
        public string PrintCenterX;
        public string PrintCenterY;
        public string PrintGrid;
        public string PrintLeftMargin;
        public string PrintPageOrientation;
        public string PrintPaperKind;
        public string PrintPaperSource;
        public string PrintRightMargin;
        public string PrintScaleX;
        public string PrintScaleY;
        public string PrintTopMargin;
        public string XGridDensity;
        public string XGridOrigin;
        public string XGridSpacing;
        public string XRulerDensity;
        public string XRulerOrigin;
        public string YGridDensity;
        public string YGridOrigin;
        public string YGridSpacing;
        public string YRulerDensity;
        public string YRulerOrigin;

        public override IEnumerable<CellTuple> GetCellTuples()
        {
            yield return new CellTuple(nameof(SRCCON.PageDrawingResizeType), SRCCON.PageDrawingResizeType, this.DrawingResizeType);
            yield return new CellTuple(nameof(SRCCON.PageDrawingScale), SRCCON.PageDrawingScale, this.DrawingScale);
            yield return new CellTuple(nameof(SRCCON.PageDrawingScaleType), SRCCON.PageDrawingScaleType, this.DrawingScaleType);
            yield return new CellTuple(nameof(SRCCON.PageDrawingSizeType), SRCCON.PageDrawingSizeType, this.DrawingSizeType);
            yield return new CellTuple(nameof(SRCCON.PageHeight), SRCCON.PageHeight, this.Height);
            yield return new CellTuple(nameof(SRCCON.PageInhibitSnap), SRCCON.PageInhibitSnap, this.InhibitSnap);
            yield return new CellTuple(nameof(SRCCON.PageLayoutAvenueSizeX), SRCCON.PageLayoutAvenueSizeX, this.LayoutAvenueSizeX);
            yield return new CellTuple(nameof(SRCCON.PageLayoutAvenueSizeY), SRCCON.PageLayoutAvenueSizeY, this.LayoutAvenueSizeY);
            yield return new CellTuple(nameof(SRCCON.PageLayoutAvoidPageBreaks), SRCCON.PageLayoutAvoidPageBreaks, this.LayoutAvoidPageBreaks);
            yield return new CellTuple(nameof(SRCCON.PageLayoutBlockSizeX), SRCCON.PageLayoutBlockSizeX, this.LayoutBlockSizeX);
            yield return new CellTuple(nameof(SRCCON.PageLayoutBlockSizeY), SRCCON.PageLayoutBlockSizeY, this.LayoutBlockSizeY);
            yield return new CellTuple(nameof(SRCCON.PageLayoutControlAsInput), SRCCON.PageLayoutControlAsInput, this.LayoutControlAsInput);
            yield return new CellTuple(nameof(SRCCON.PageLayoutDynamicsOff), SRCCON.PageLayoutDynamicsOff, this.LayoutDynamicsOff);
            yield return new CellTuple(nameof(SRCCON.PageLayoutEnableGrid), SRCCON.PageLayoutEnableGrid, this.LayoutEnableGrid);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineAdjustFrom), SRCCON.PageLayoutLineAdjustFrom, this.LayoutLineAdjustFrom);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineAdjustTo), SRCCON.PageLayoutLineAdjustTo, this.LayoutLineAdjustTo);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineJumpCode), SRCCON.PageLayoutLineJumpCode, this.LayoutLineJumpCode);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineJumpDirX), SRCCON.PageLayoutLineJumpDirX, this.LayoutLineJumpDirX);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineJumpDirY), SRCCON.PageLayoutLineJumpDirY, this.LayoutLineJumpDirY);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineJumpFactorX), SRCCON.PageLayoutLineJumpFactorX, this.LayoutLineJumpFactorX);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineJumpFactorY), SRCCON.PageLayoutLineJumpFactorY, this.LayoutLineJumpFactorY);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineJumpStyle), SRCCON.PageLayoutLineJumpStyle, this.LayoutLineJumpStyle);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineRouteExt), SRCCON.PageLayoutLineRouteExt, this.LayoutLineRouteExt);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineToLineX), SRCCON.PageLayoutLineToLineX, this.LayoutLineToLineX);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineToLineY), SRCCON.PageLayoutLineToLineY, this.LayoutLineToLineY);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineToNodeX), SRCCON.PageLayoutLineToNodeX, this.LayoutLineToNodeX);
            yield return new CellTuple(nameof(SRCCON.PageLayoutLineToNodeY), SRCCON.PageLayoutLineToNodeY, this.LayoutLineToNodeY);
            yield return new CellTuple(nameof(SRCCON.PageLayoutPlaceDepth), SRCCON.PageLayoutPlaceDepth, this.LayoutPlaceDepth);
            yield return new CellTuple(nameof(SRCCON.PageLayoutPlaceFlip), SRCCON.PageLayoutPlaceFlip, this.LayoutPlaceFlip);
            yield return new CellTuple(nameof(SRCCON.PageLayoutPlaceStyle), SRCCON.PageLayoutPlaceStyle, this.LayoutPlaceStyle);
            yield return new CellTuple(nameof(SRCCON.PageLayoutPlowCode), SRCCON.PageLayoutPlowCode, this.LayoutPlowCode);
            yield return new CellTuple(nameof(SRCCON.PageLayoutResizePage), SRCCON.PageLayoutResizePage, this.LayoutResizePage);
            yield return new CellTuple(nameof(SRCCON.PageLayoutRouteStyle), SRCCON.PageLayoutRouteStyle, this.LayoutRouteStyle);
            yield return new CellTuple(nameof(SRCCON.PageLayoutShapeSplit), SRCCON.PageLayoutShapeSplit, this.LayoutShapeSplit);
            yield return new CellTuple(nameof(SRCCON.PageScale), SRCCON.PageScale, this.Scale);
            yield return new CellTuple(nameof(SRCCON.PageShadowObliqueAngle), SRCCON.PageShadowObliqueAngle, this.ShadowObliqueAngle);
            yield return new CellTuple(nameof(SRCCON.PageShadowOffsetX), SRCCON.PageShadowOffsetX, this.ShadowOffsetX);
            yield return new CellTuple(nameof(SRCCON.PageShadowOffsetY), SRCCON.PageShadowOffsetY, this.ShadowOffsetY);
            yield return new CellTuple(nameof(SRCCON.PageShadowScaleFactor), SRCCON.PageShadowScaleFactor, this.ShadowScaleFactor);
            yield return new CellTuple(nameof(SRCCON.PageShadowType), SRCCON.PageShadowType, this.ShadowType);
            yield return new CellTuple(nameof(SRCCON.PageUIVisibility), SRCCON.PageUIVisibility, this.UIVisibility);
            yield return new CellTuple(nameof(SRCCON.PageWidth), SRCCON.PageWidth, this.Width);
            yield return new CellTuple(nameof(SRCCON.PrintBottomMargin), SRCCON.PrintBottomMargin, this.BottomMargin);
            yield return new CellTuple(nameof(SRCCON.PrintCenterX), SRCCON.PrintCenterX, this.PrintCenterX);
            yield return new CellTuple(nameof(SRCCON.PrintCenterY), SRCCON.PrintCenterY, this.PrintCenterY);
            yield return new CellTuple(nameof(SRCCON.PrintGrid), SRCCON.PrintGrid, this.PrintGrid);
            yield return new CellTuple(nameof(SRCCON.PrintLeftMargin), SRCCON.PrintLeftMargin, this.PrintLeftMargin);
            yield return new CellTuple(nameof(SRCCON.PrintPageOrientation), SRCCON.PrintPageOrientation, this.PrintPageOrientation);
            yield return new CellTuple(nameof(SRCCON.PrintPaperKind), SRCCON.PrintPaperKind, this.PrintPaperKind);
            yield return new CellTuple(nameof(SRCCON.PrintPaperSource), SRCCON.PrintPaperSource, this.PrintPaperSource);
            yield return new CellTuple(nameof(SRCCON.PrintRightMargin), SRCCON.PrintRightMargin, this.PrintRightMargin);
            yield return new CellTuple(nameof(SRCCON.PrintScaleX), SRCCON.PrintScaleX, this.PrintScaleX);
            yield return new CellTuple(nameof(SRCCON.PrintScaleY), SRCCON.PrintScaleY, this.PrintScaleY);
            yield return new CellTuple(nameof(SRCCON.PrintTopMargin), SRCCON.PrintTopMargin, this.PrintTopMargin);
            yield return new CellTuple(nameof(SRCCON.XGridDensity), SRCCON.XGridDensity, this.XGridDensity);
            yield return new CellTuple(nameof(SRCCON.XGridOrigin), SRCCON.XGridOrigin, this.XGridOrigin);
            yield return new CellTuple(nameof(SRCCON.XGridSpacing), SRCCON.XGridSpacing, this.XGridSpacing);
            yield return new CellTuple(nameof(SRCCON.XRulerDensity), SRCCON.XRulerDensity, this.XRulerDensity);
            yield return new CellTuple(nameof(SRCCON.XRulerOrigin), SRCCON.XRulerOrigin, this.XRulerOrigin);
            yield return new CellTuple(nameof(SRCCON.YGridDensity), SRCCON.YGridDensity, this.YGridDensity);
            yield return new CellTuple(nameof(SRCCON.YGridOrigin), SRCCON.YGridOrigin, this.YGridOrigin);
            yield return new CellTuple(nameof(SRCCON.YGridSpacing), SRCCON.YGridSpacing, this.YGridSpacing);
            yield return new CellTuple(nameof(SRCCON.YRulerDensity), SRCCON.YRulerDensity, this.YRulerDensity);
            yield return new CellTuple(nameof(SRCCON.YRulerOrigin), SRCCON.YRulerOrigin, this.YRulerOrigin);
        }

    }
}
