//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisioAutomation.VDX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisioAutomation.VDX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos; ?&gt;
        ///&lt;VisioDocument key=&apos;5152879C9DD5F24A7594B21E4E1210A150A936B8F40484352291414D8C78B2E13C292BE7699B9A8C38A519316455C1C6E8655150856D15657817CFDB8C64F769&apos; start=&apos;190&apos; metric=&apos;0&apos; DocLangID=&apos;1033&apos; buildnum=&apos;6423&apos; version=&apos;12.0&apos; xml:space=&apos;preserve&apos; xmlns=&apos;http://schemas.microsoft.com/visio/2003/core&apos; xmlns:vx=&apos;http://schemas.microsoft.com/visio/2006/extension&apos;&gt;&lt;DocumentProperties&gt;&lt;Creator&gt;Saveen Reddy&lt;/Creator&gt;&lt;Company&gt;Microsoft&lt;/Company&gt;&lt;BuildNumberCreated&gt;805312791&lt;/Build [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultVDXTemplate {
            get {
                return ResourceManager.GetString("DefaultVDXTemplate", resourceCulture);
            }
        }
        
        internal static byte[] Template {
            get {
                object obj = ResourceManager.GetObject("Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
